"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import TopBar from "@/components/TopBar";
import BottomNav from "@/components/BottomNav";
import Skeleton from "@/components/Skeleton";
import AppIcon from "@/components/ui/AppIcon";
import { ApiFetchError } from "@/lib/apiCache";
import { getMaintenancePanel } from "@/lib/maintenancePanel";
import { forecastDaysFromRemainingHours } from "@/lib/forecastMath";
import type { PanelItem, StatusKey } from "@/lib/status";

const statusLabel: Record<string, string> = { gecikmis: "Gecikmiş", kritik: "Kritik", yaklasiyor: "Yaklaşıyor", normal: "Normal" };
const statusClass: Record<string, string> = { gecikmis: "text-red border-red/30 bg-red/5", kritik: "text-orange border-orange/30 bg-orange/5", yaklasiyor: "text-amber border-amber/30 bg-amber/5", normal: "text-green border-green/30 bg-green/5" };
type Plan = { engine_id: string; type_key: string; planned_date: string; status: "planned" | "in_progress" | "completed" | "cancelled"; technician_id?: string; note?: string };
type Technician = { id: string; full_name: string };

function dateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function forecastDate(item: PanelItem) {
  const date = new Date();
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() + forecastDaysFromRemainingHours(item.remaining));
  return date;
}

export default function TakvimPage() {
  const router = useRouter();
  const [items, setItems] = useState<PanelItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [monthDate, setMonthDate] = useState(() => new Date());
  const [status, setStatus] = useState<"all" | StatusKey>("all");
  const [engine, setEngine] = useState("all");
  const [plans, setPlans] = useState<Plan[]>([]);
  const [technicians, setTechnicians] = useState<Technician[]>([]);
  const [editingPlan, setEditingPlan] = useState<PanelItem | null>(null);
  const [planDate, setPlanDate] = useState("");
  const [planStatus, setPlanStatus] = useState<Plan["status"]>("planned");
  const [planTechnician, setPlanTechnician] = useState("");
  const [planNote, setPlanNote] = useState("");
  const [savingPlan, setSavingPlan] = useState(false);

  useEffect(() => { Promise.all([getMaintenancePanel(), fetch("/api/plans"), fetch("/api/users/technicians")]).then(async ([data, plansResponse, techniciansResponse]) => { setItems(data.items || []); if (plansResponse.ok) setPlans(await plansResponse.json()); if (techniciansResponse.ok) setTechnicians(await techniciansResponse.json()); setLoading(false); }).catch((error) => { if (error instanceof ApiFetchError && error.status === 401) router.push("/login"); else setLoading(false); }); }, [router]);

  const engines = useMemo(() => [...new Map(items.map((item) => [item.engine_id, item.engine_name])).entries()].sort((a, b) => a[1].localeCompare(b[1], "tr")), [items]);
  const filtered = useMemo(() => items.filter((item) => (status === "all" || item.status === status) && (engine === "all" || item.engine_id === engine)), [items, status, engine]);
  const planMap = useMemo(() => new Map(plans.map((plan) => [`${plan.engine_id}:${plan.type_key}`, plan])), [plans]);
  const byDate = useMemo(() => { const map = new Map<string, PanelItem[]>(); filtered.forEach((item) => { const plan = planMap.get(`${item.engine_id}:${item.type_key}`); const key = plan?.planned_date || dateKey(forecastDate(item)); map.set(key, [...(map.get(key) || []), item]); }); return map; }, [filtered, planMap]);
  const monthDays = useMemo(() => { const first = new Date(monthDate.getFullYear(), monthDate.getMonth(), 1); const offset = (first.getDay() + 6) % 7; const days = new Date(monthDate.getFullYear(), monthDate.getMonth() + 1, 0).getDate(); return Array.from({ length: Math.ceil((offset + days) / 7) * 7 }, (_, index) => { const day = index - offset + 1; return day < 1 || day > days ? null : new Date(monthDate.getFullYear(), monthDate.getMonth(), day); }); }, [monthDate]);
  const monthTitle = new Intl.DateTimeFormat("tr-TR", { month: "long", year: "numeric" }).format(monthDate);
  const summary = { overdue: filtered.filter((item) => item.status === "gecikmis").length, urgent: filtered.filter((item) => item.status === "kritik" || item.status === "yaklasiyor").length };
  function openPlan(item: PanelItem) { const plan = planMap.get(`${item.engine_id}:${item.type_key}`); setEditingPlan(item); setPlanDate(plan?.planned_date || dateKey(forecastDate(item))); setPlanStatus(plan?.status || "planned"); setPlanTechnician(plan?.technician_id || ""); setPlanNote(plan?.note || ""); }
  async function savePlan() { if (!editingPlan || !planDate) return; setSavingPlan(true); try { const response = await fetch("/api/plans", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ engine_id: editingPlan.engine_id, type_key: editingPlan.type_key, planned_date: planDate, status: planStatus, technician_id: planTechnician, note: planNote }) }); if (!response.ok) throw new Error("Plan kaydedilemedi."); const saved = await response.json() as Plan; setPlans((current) => [...current.filter((plan) => `${plan.engine_id}:${plan.type_key}` !== `${saved.engine_id}:${saved.type_key}`), saved]); setEditingPlan(null); } catch { window.alert("Plan kaydedilemedi. Lütfen tekrar deneyin."); } finally { setSavingPlan(false); } }

  if (loading) return <><TopBar title="Bakım Takvimi" subtitle="Yükleniyor..." /><div className="p-4"><Skeleton className="h-40 rounded-card" /></div><BottomNav /></>;
  return <div><TopBar title="Bakım Takvimi" subtitle="Saat bazlı tahmini plan" /><main className="px-4 py-4">
    <section className="rounded-card border border-amber/20 bg-gradient-to-br from-amber/10 via-panel to-panel p-4"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-amber"><AppIcon name="calendar" size={16} /><span className="text-[10px] font-bold uppercase tracking-[0.14em]">Planlama merkezi</span></div><h1 className="mt-1 text-[15px] font-bold text-text">Yaklaşan bakımlar</h1><p className="mt-1 text-[11px] leading-4 text-muted">Motor kullanım hızına göre tahmini tarihler. Tarihleri planlama kararı vermeden önce ekip takvimiyle doğrulayın.</p></div><div className="text-right"><div className="font-mono text-lg font-bold text-text">{filtered.length}</div><div className="text-[9px] text-faint">görev</div></div></div></section>
    <div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-control border border-red/25 bg-red/5 p-2.5"><div className="text-[9px] uppercase text-faint">Gecikmiş</div><div className="mt-1 font-mono text-lg font-bold text-red">{summary.overdue}</div></div><div className="rounded-control border border-amber/25 bg-amber/5 p-2.5"><div className="text-[9px] uppercase text-faint">Yaklaşan</div><div className="mt-1 font-mono text-lg font-bold text-amber">{summary.urgent}</div></div></div>
    <div className="mt-3 grid gap-2 sm:grid-cols-2"><select aria-label="Motor filtresi" value={engine} onChange={(e) => setEngine(e.target.value)} className="min-h-11 rounded-control border border-border bg-panel2 px-3 text-xs text-text"><option value="all">Tüm motorlar</option>{engines.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select aria-label="Durum filtresi" value={status} onChange={(e) => setStatus(e.target.value as "all" | StatusKey)} className="min-h-11 rounded-control border border-border bg-panel2 px-3 text-xs text-text"><option value="all">Tüm durumlar</option>{Object.entries(statusLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div>
    <section className="mt-4 rounded-card border border-border bg-panel p-3"><div className="mb-3 flex items-center justify-between"><button aria-label="Önceki ay" onClick={() => setMonthDate(new Date(monthDate.getFullYear(), monthDate.getMonth() - 1, 1))} className="min-h-11 min-w-11 rounded-control border border-border text-lg text-muted hover:text-text">‹</button><h2 className="text-sm font-bold capitalize text-text">{monthTitle}</h2><button aria-label="Sonraki ay" onClick={() => setMonthDate(new Date(monthDate.getFullYear(), monthDate.getMonth() + 1, 1))} className="min-h-11 min-w-11 rounded-control border border-border text-lg text-muted hover:text-text">›</button></div><div className="grid grid-cols-7 gap-1 text-center text-[9px] font-bold uppercase text-faint">{["Pzt", "Sal", "Çar", "Per", "Cum", "Cmt", "Paz"].map((day) => <span key={day}>{day}</span>)}</div><div className="mt-1 grid grid-cols-7 gap-1">{monthDays.map((day, index) => { const tasks = day ? byDate.get(dateKey(day)) || [] : []; return <div key={index} className={`min-h-16 rounded-lg border p-1 ${day ? "border-border bg-panel2" : "border-transparent bg-transparent"}`}><div className="text-right text-[9px] text-faint">{day?.getDate()}</div>{tasks.slice(0, 2).map((item) => <button key={`${item.engine_id}-${item.type_key}`} onClick={() => openPlan(item)} className={`mt-0.5 block w-full truncate rounded border px-1 py-0.5 text-left text-[8px] font-bold ${statusClass[item.status]}`}>{item.engine_name} · {item.type_label}</button>)}{tasks.length > 2 && <div className="px-1 text-[8px] text-faint">+{tasks.length - 2} görev</div>}</div>; })}</div></section>
    <section className="mt-4 space-y-2">{filtered.sort((a, b) => a.remaining - b.remaining).map((item) => { const plan = planMap.get(`${item.engine_id}:${item.type_key}`); return <article key={`${item.engine_id}-${item.type_key}`} className="rounded-card border border-border bg-panel p-3"><div className="flex items-start justify-between gap-3"><div><div className="text-[13px] font-bold text-text">{item.engine_name}</div><div className="mt-0.5 text-[11px] text-muted">{item.type_label} · {plan ? `Planlanan ${new Date(`${plan.planned_date}T00:00:00`).toLocaleDateString("tr-TR")}` : `Tahmini ${forecastDate(item).toLocaleDateString("tr-TR")}`}</div>{plan?.technician_id && <div className="mt-1 text-[10px] text-teal">Sorumlu: {technicians.find((technician) => technician.id === plan.technician_id)?.full_name || "Atandı"}</div>}</div><span className={`rounded-full border px-2 py-1 text-[10px] font-bold ${statusClass[item.status]}`}>{plan?.status === "in_progress" ? "Devam ediyor" : plan?.status === "completed" ? "Tamamlandı" : statusLabel[item.status]}</span></div><div className="mt-3 flex items-center justify-between border-t border-border pt-2"><span className="text-[11px] text-faint">Motor saati: {item.engine_hours.toLocaleString("tr-TR")}</span><button onClick={() => openPlan(item)} className="min-h-11 rounded-control bg-amber px-3 text-[11px] font-bold text-slate-950">{plan ? "Planı düzenle" : "Planla"}</button></div></article>; })}{filtered.length === 0 && <div className="rounded-card border border-dashed border-border p-8 text-center text-xs text-muted">Bu filtrelerle eşleşen plan bulunamadı.</div>}</section>
    {editingPlan && <div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/70 p-3 sm:items-center"><section role="dialog" aria-modal="true" aria-labelledby="plan-editor-title" className="w-full max-w-lg rounded-card border border-border bg-panel p-4 shadow-2xl"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-wide text-amber">Gerçek plan</div><h2 id="plan-editor-title" className="mt-1 text-base font-bold text-text">{editingPlan.engine_name} · {editingPlan.type_label}</h2></div><button onClick={() => setEditingPlan(null)} aria-label="Plan düzenleyiciyi kapat" className="min-h-11 min-w-11 rounded-control border border-border text-lg text-muted">×</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-[10px] font-bold uppercase text-muted">Plan tarihi<input type="date" value={planDate} onChange={(event) => setPlanDate(event.target.value)} className="mt-1.5 min-h-11 w-full rounded-control border border-border bg-panel2 px-3 text-sm text-text" /></label><label className="text-[10px] font-bold uppercase text-muted">Plan durumu<select value={planStatus} onChange={(event) => setPlanStatus(event.target.value as Plan["status"])} className="mt-1.5 min-h-11 w-full rounded-control border border-border bg-panel2 px-3 text-sm text-text"><option value="planned">Planlandı</option><option value="in_progress">Devam ediyor</option><option value="completed">Tamamlandı</option><option value="cancelled">İptal edildi</option></select></label></div><label className="mt-3 block text-[10px] font-bold uppercase text-muted">Sorumlu teknisyen<select value={planTechnician} onChange={(event) => setPlanTechnician(event.target.value)} className="mt-1.5 min-h-11 w-full rounded-control border border-border bg-panel2 px-3 text-sm text-text"><option value="">Atanmadı</option>{technicians.map((technician) => <option key={technician.id} value={technician.id}>{technician.full_name}</option>)}</select></label><label className="mt-3 block text-[10px] font-bold uppercase text-muted">Plan notu<textarea value={planNote} onChange={(event) => setPlanNote(event.target.value)} maxLength={500} rows={3} className="mt-1.5 w-full rounded-control border border-border bg-panel2 px-3 py-2.5 text-sm text-text" /></label><div className="mt-4 flex justify-end gap-2"><button onClick={() => setEditingPlan(null)} className="min-h-11 rounded-control border border-border px-4 text-xs font-bold text-muted">Vazgeç</button><button disabled={savingPlan || !planDate} onClick={() => void savePlan()} className="min-h-11 rounded-control bg-amber px-4 text-xs font-bold text-slate-950">{savingPlan ? "Kaydediliyor..." : "Planı kaydet"}</button></div></section></div>}
  </main><BottomNav /></div>;
}
