"use client";
import { useEffect, useState } from "react";
import AppIcon from "@/components/ui/AppIcon";
type Risk = { engine_id: string; engine: string; score: number; level: "low" | "watch" | "high" | "critical"; reasons: string[]; attention: number };
type Payload = { summary: string; methodology: string; recommendations: string[]; risks: Risk[] };
const levelLabel = { low: "Düşük", watch: "İzlenmeli", high: "Yüksek", critical: "Kritik" };
const levelClass = { low: "text-green", watch: "text-amber", high: "text-orange", critical: "text-red" };
export default function DashboardAiBrief() {
  const [data, setData] = useState<Payload | null>(null);
  useEffect(() => { fetch("/api/ai/insights", { cache: "no-store" }).then((response) => response.ok ? response.json() : null).then((value) => { if (value) setData(value); }).catch(() => {}); }, []);
  if (!data) return null;
  return <section className="mb-4 rounded-card border border-teal/25 bg-gradient-to-br from-teal/10 via-panel to-panel p-4" aria-labelledby="ai-brief-heading"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 text-teal"><AppIcon name="assistant" size={16} /><span className="text-[10px] font-bold uppercase tracking-[0.14em]">Akıllı operasyon özeti</span></div><h2 id="ai-brief-heading" className="mt-1 text-[14px] font-bold text-text">Bugünün karar desteği</h2><p className="mt-1 text-[11px] text-muted">{data.summary}</p></div><span className="rounded-full border border-teal/30 bg-teal/10 px-2 py-1 text-[9px] font-bold text-teal">SALT OKUNUR</span></div><div className="mt-3 grid gap-2 md:grid-cols-2">{data.risks.slice(0, 4).map((risk) => <div key={risk.engine_id} className="rounded-control border border-border bg-panel2 p-2.5"><div className="flex items-center justify-between gap-2"><span className="truncate text-[11px] font-bold text-text">{risk.engine}</span><span className={`font-mono text-[11px] font-bold ${levelClass[risk.level]}`}>%{risk.score} · {levelLabel[risk.level]}</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-bg"><div className={`h-full ${risk.level === "critical" ? "bg-red" : risk.level === "high" ? "bg-orange" : risk.level === "watch" ? "bg-amber" : "bg-green"}`} style={{ width: `${risk.score}%` }} /></div><p className="mt-1.5 text-[9.5px] leading-4 text-faint">{risk.reasons.join(" · ") || "Acil sinyal yok"}</p></div>)}</div><div className="mt-3 border-t border-border/70 pt-3"><div className="text-[10px] font-bold uppercase tracking-wide text-faint">Önerilen aksiyonlar</div><ul className="mt-1 space-y-1 text-[10.5px] leading-4 text-muted">{data.recommendations.slice(0, 3).map((recommendation) => <li key={recommendation}>• {recommendation}</li>)}</ul></div><p className="mt-3 text-[9px] text-faint">{data.methodology}</p></section>;
}
